/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EmailListItem: typeof import('./src/components/EmailListItem.vue')['default']
    EmailPlainTextViewer: typeof import('./src/components/EmailViewer/EmailPlainTextViewer.vue')['default']
    EmailViewer: typeof import('./src/components/EmailViewer.vue')['default']
    GlobalSearch: typeof import('./src/components/GlobalSearch.vue')['default']
    LanguageSettings: typeof import('./src/components/LanguageSettings.vue')['default']
    MissingImage: typeof import('./src/components/MissingImage.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    ThemeSettings: typeof import('./src/components/ThemeSettings.vue')['default']
  }
}
